source 'https://github.com/CocoaPods/Specs.git'

target 'PXIconTextView', :exclusive => true do
  pod "PXIconTextView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXIconTextView", :path => "../"


end
